/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoestoque.telas;

import br.com.projetoestoque.dal.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jdavi
 */
public class TelaAlterar extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement stmt = null;
    /**
     * Creates new form TelaAlterar
     */
    public TelaAlterar() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    
    private void alterar() {
        String sql = "update tbproduto set preco=?, quantidade=? where idprod=?";
        
        try {
            stmt = conexao.prepareStatement(sql);
            stmt.setString(3,txtProId.getText());
            stmt.setString(1,txtProValor.getText());
            stmt.setString(2,txtProQuant.getText());
            if(((txtProId.getText().isEmpty())||(txtProQuant.getText().isEmpty())||txtProValor.getText().isEmpty())){
                JOptionPane.showInternalMessageDialog(this, "Preencher todos os campos obrigatórios!");
                
            }else{
                
            int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja alterar?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION){
                stmt.executeUpdate();
                JOptionPane.showInternalMessageDialog(this, "Produto alterado com sucesso!");
                txtProId.setText(null);
                txtProQuant.setText(null);
                txtProValor.setText(null);
                
            
    }
            
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProId = new javax.swing.JTextField();
        btn_adc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtProValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProQuant = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alterar");
        setPreferredSize(new java.awt.Dimension(640, 480));

        btn_adc.setText("Confirmar");
        btn_adc.setToolTipText("Adicionar");
        btn_adc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adc.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_adc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adcActionPerformed(evt);
            }
        });

        jLabel3.setText("* Valor");

        txtProValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProValorActionPerformed(evt);
            }
        });

        jLabel5.setText("* Quantidade");

        jLabel1.setText("* Id");

        jLabel2.setText("* Campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_adc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(txtProQuant, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_adc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adcActionPerformed
        alterar();
    }//GEN-LAST:event_btn_adcActionPerformed

    private void txtProValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtProId;
    private javax.swing.JTextField txtProQuant;
    private javax.swing.JTextField txtProValor;
    // End of variables declaration//GEN-END:variables
}
